# helm-values/harbor-values.yaml
expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    ports:
      http:
        port: 80
        nodePort: 30080
      https:
        port: 443
        nodeport: 30443
externalURL: http://192.168.187.128:30080   # 必须改成你实际访问地址

persistence:
  enabled: false

harborAdminPassword: "050919"   # 强烈建议改成强密码

logLevel: info

# 关闭不必要的组件（实验环境节省资源）
trivy:
  enabled: false   # 漏洞扫描，实验可先关
chartmuseum:
  enabled: false
notary:
  enabled: false
